# Generated by Django 5.2.4 on 2025-07-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discente', models.CharField(max_length=100)),
                ('turma', models.CharField(choices=[('ADM1', '1º ano de Administração'), ('ADM2', '2º ano de Administração'), ('INF1', '1º ano de Informática'), ('INF2', '2º ano de Informática'), ('INF3', '3º ano de Informática'), ('ADMSUB', 'Administração subsequente'), ('INFSUB', 'Informática subsequente'), ('SECSUB', 'Secretariado subsequente')], max_length=6)),
                ('data', models.DateField()),
                ('mensagem', models.TextField(verbose_name='Solicitação ou dúvida')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
