# Generated by Django 5.2.4 on 2025-07-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discente', models.CharField(max_length=100)),
                ('alunos_envolvidos', models.TextField()),
                ('matricula', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ocorrencia', models.DateField()),
                ('hora', models.TimeField()),
                ('local_ocorrencia', models.CharField(max_length=200)),
                ('atitudes_inadequadas', models.TextField()),
                ('envolvidos_ocorrencia', models.TextField()),
                ('relato_ocorrencia', models.TextField()),
                ('evidencias', models.TextField(blank=True, null=True)),
                ('ha_testemunhas', models.BooleanField(default=False)),
                ('despacho_cae', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
