# Generated by Django 5.2.4 on 2025-07-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('turma', models.CharField(choices=[('1_ADM', '1º Ano de Administração'), ('2_ADM', '2º Ano de Administração'), ('1_INF', '1º Ano de Informática'), ('2_INF', '2º Ano de Informática'), ('3_INF', '3º Ano de Informática'), ('SUB_ADM', 'Administração Subsequente'), ('SUB_INF', 'Informática Subsequente'), ('SUB_SEC', 'Secretariado Subsequente')], max_length=10)),
                ('data_atendimento', models.DateField()),
                ('despacho_cae', models.CharField(choices=[('NUE', 'NUE'), ('CD', 'Comissão Disciplinar')], max_length=3)),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('motivo', models.CharField(max_length=255)),
                ('descricao_ocorrencia', models.TextField()),
            ],
        ),
    ]
