# Generated by Django 5.2.4 on 2025-07-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='discente',
            field=models.CharField(default='Fulano', max_length=100),
            preserve_default=False,
        ),
    ]
